hf_configuration:
  hf_dataset_name: yourbench_example
  private: false

model_list:
  - model_name: Qwen/Qwen3-30B-A3B
    provider: fireworks-ai

pipeline:
  resume: true
  cache_dir: pipeline_cache
  reset_cache: false
  ingestion:
    source_documents_dir: example/data/raw
    output_dir: example/data/processed
  upload_ingest_to_hub:
  summarization:
  chunking:
  single_shot_question_generation:
  multi_hop_question_generation:
  lighteval:
  citation_score_filtering:
